### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by manuiade** [webhookrelay/webhookrelay-operator#17]
Hello, are you planning to provide a multi arch image for arm64 architectures? Thanks in advance

**Comment by rusenask** [comment]
Hi, definitely!

**Comment by manuiade** [comment]
Thanks for the quick reply, I'll wait then, keep me notified thanks ;)

**Comment by GraemeF** [comment]
Hello! Sooooo... any sign of this?

**Comment by rusenask** [comment]
let's do this today 🚀
