### ISSUE TITLE
Link / URL Broken - In the docs the link about howe to use kubernets is broken

### ISSUE THREAD

**Issue by pentateu** [webhookrelay/webhookrelay-operator#18]
https://docs.webhookrelay.com/products/tunnels/tunnels#tunnels-for-kubernetes
On the page above, at the bottom in the kubernets session has a broken link: https://github.com/rusenask/webrelay-landing/blob/1.0.0/v1/guide/ingress-controller.html

I assume it should point to this  repository ?

Cheers

**Comment by rusenask** [comment]
thank you!
